### PR TITLE
Add Circle of the Dragon & Kibbles Tasty Dragon Patron

### PR DESCRIPTION
**Pull request by revilowaldow**
A Druid Circle featuring a dragon wildshape.

### CODE REVIEW

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
@revilowaldow merged an earlier PR which has caused some conflicts; apologies. Please fix.

**Comment by revilowaldow** [comment]
No problem, will resolve later this week

**Review by TheGiddyLimit — APPROVED** [review]

**Review by TheGiddyLimit — COMMENTED** [review]
in order to hide your shame in future
```
git commit --amend
git push --force
```

**Comment by revilowaldow** [comment]
```
git commit --amend
git push --force
```

What is this dark shell magic? I only use buttons :KEKW:
Thanks ❤

**Pull request merged**
