### PR TITLE
Fixed wording

### PR DESCRIPTION
**Pull request by silverbass**

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Conflicts 🔥

**Comment by TheGiddyLimit** [comment]
And again :fire:

**Comment by silverbass** [comment]
Idk if this fixes it but if this is an issue again, then I'll just close and reopen it

**Comment by TheGiddyLimit** [comment]
No changes, huh? I guess you already made the same changes in another PR?

**Comment by silverbass** [comment]
Possibly

**Pull request closed without merging**
