### PR TITLE
Taggerinos and taggaritos

### PR DESCRIPTION
**Pull request by Spappz**
Fixed tags on all my files plus a whole bunch of other ones I have a soft spot for.

Also moved `Monte Cook; Arcana of the Ancients.json` from `book` to `collection` for accuracy, and edited the `full` of MME1 for clarity.

### CODE REVIEW

**Comment by Spappz** [comment]
Oh also I pushed an updated `package-lock.json`

**Comment by revilowaldow** [comment]
> Oh also I pushed an updated `package-lock.json`

Un-push it. :gunR:

**Comment by revilowaldow** [comment]
image
Mate what are you doing

**Comment by Spappz** [comment]
> Un-push it. :gunR:

npm are very clear that `package-lock.json` should be pushed m890 haven't you even read the docs

> Mate what are you doing

making one small regex error out of the ~250 errors i otherwise fixed, what are _you_ doing :gunR:

**Comment by revilowaldow** [comment]
> npm are very clear that `package-lock.json` should be pushed m890 haven't you even read the docs

Yeah, by the owner of the repo.
Cheers for deleting all the dependencies out of the package lock, sure that'll really help everyone else 👌

**Comment by Spappz** [comment]
>  Cheers for deleting all the dependencies out of the package lock, sure that'll really help everyone else 👌

you're welcome, it was a [legacy format](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#dependencies) after all

**Comment by Spappz** [comment]
merged into lyra's PR (except for `package-lock.json` 😢)

**Pull request closed without merging**
