### PR TITLE
Add Keys from the Golden Vault Calling Cards

### PR DESCRIPTION
**Pull request by revilowaldow**
Taken from the quiz at the bottom of this page:
https://dnd.wizards.com/products/keys-from-the-golden-vault
image
image

### CODE REVIEW

**Review by TheGiddyLimit — APPROVED** [review]
💪

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
Colons in filenames break Windows 🙃

**Comment by revilowaldow** [comment]
😭 will fix that tomorrow evening when I'm at a pc

**Review by TheGiddyLimit — APPROVED** [review]
🪟 

(ironically this shows as a missing-character-square on my Windows machine)

**Pull request merged**
