### PR TITLE
SRD, Homebrew Conversion Updates

### PR DESCRIPTION
**Pull request by DMsGuild201**

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
FYI, files should be `.json` instead of `.JSON`, because Linux' filesystem is case-sensitive. If you're on Windows, the only way I know to get Git to catch on, is to rename the file to something random -> commit it -> rename it back to the correct, lowercase-extension, name -> commit it again.

**Comment by DMsGuild201** [comment]
I am on windows. will do

**Comment by TheGiddyLimit** [comment]
:+1: 
And of course, there are some merge conflicts to fix :joy:

**Comment by TheGiddyLimit** [comment]
Lovely. Still a conflict in the SRD file, however?

**Comment by DMsGuild201** [comment]
Yeah this one is the one we want... we know the one you have has errors... sorry.

Nekka pointed out that its just bad.

**Pull request merged**
