### PR TITLE
FIX AGAIN

### PR DESCRIPTION
**Pull request by revilowaldow**
This is yet more fixes for Odyssey of the Dragonlords.

@shadowslasher410 please can you check as you go, and ideally use this file as the starting point for any further work you do

### CODE REVIEW

**Comment by shadowslasher410** [comment]
Will check out in depth tomorrow (have D&D session in half an hour. Regardless of the JSON, there are a couple of images with white borders that I fixed that I need to commit as well, which I will when I finish checking the new one out).

**Comment by revilowaldow** [comment]
No worries. FYI the first commit just automatically puts everything in a standard sorted order so it's easier to find things. The second commit is the actual fixes 👍 enjoy your session

**Comment by shadowslasher410** [comment]
Wait... there's a standard sorted order? I just did it alphabetically... Where would I find that? Is it in the schema?

**Comment by revilowaldow** [comment]
It's a feature of the site that requires you have a copy of that downloaded as well. It's a bit more nuanced than "just alphabetical", for example class features are sorted by:
- class source
- then class name
- then feature level
- then feature name
- then feature source
 so they're in a sensible order.

image

**Comment by revilowaldow** [comment]
https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/blob/main/js/utils-proporder.js

**Comment by shadowslasher410** [comment]
So, I fixed/added the changes and updated my fork, but for some stupid reason, it has some other files changed too even though I didn't touch them. The only ones that should be changed are the image files and the OOTD JSON.

Oh, and as an aside, I'm pretty sure the homebrew's package.json needs to be updated too, with the latest versions of commander and 5eutils.

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
my bad; didn't bother to check out the mega-diff locally, and it doesn't load in a browser

**Pull request merged**
