### PR TITLE
feat(json): Add BREW-547, -545, -350 and Illithid Race

### PR DESCRIPTION
**Pull request by revilowaldow**
BREW-545 hopefully coming soon

### CODE REVIEW

**Comment by revilowaldow** [comment]
Currently the modified version of this is breaking the classes page due to an issue with dependencies. Needs review by Giddy.

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
Seems to be mostly a bug with the logging; the problem is that you've named the class `"Nomad (Modified)"`, but have `className: "Nomad"` on all your features, so things don't match up

**Comment by revilowaldow** [comment]
Ahhh I see, so the issue is that I'm a fucking moron.

**Comment by revilowaldow** [comment]
Thank you for your assistance, will fix this tomorrow. 🙇‍♂️

**Comment by revilowaldow** [comment]
@TheGiddyLimit All done, cheers for your help, please watch out for the modified index files (necessary for testing) when merging.

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
