### PR TITLE
Minor Updates to Lera & Blood in the Company

### PR DESCRIPTION
**Pull request by revilowaldow**

### CODE REVIEW

**Comment by revilowaldow** [comment]
I believe this failed because I renamed the file and it thinks there's already a homebrew with the source reserved, but its just the same one.

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
Files should be `.json` and not `.JSON`

**Comment by revilowaldow** [comment]
> Files should be `.json` and not `.JSON`

Resolved

**Comment by TheGiddyLimit** [comment]
Seems you've now got some merge conflicts

**Comment by revilowaldow** [comment]
I have no idea what's causing the conflict.

**Pull request closed without merging**
