### PR TITLE
Binder (Foundry featured)

### PR DESCRIPTION
**Pull request by SLankoff**
Has a flags system with a macro for proper operation. Let me know if there's a good place to include that?

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
if it's something which could be an [_item_ macro](https://foundryvtt.com/packages/itemacro), then it could get added the the [Automation Addon repo](https://github.com/TheGiddyLimit/plutonium-addon-automation/blob/master/CONTRIBUTING.md#macros).

If not, then things get awkward. Post the macro/a link to the macro here, and we'll see?

**Comment by SLankoff** [comment]
Sounds like it'll be awkward then... lol.
It's for importing and rotating optionalFeatures that they're allowed to swap on a long rest. You made me the import feature btw.

`const URL_BREW = `${final_brew_url_}`;
let targetactor = token.actor;
  let targetitems = targetactor.items;
  if (!targetactor.system.scale.binder)
  {
      ui.notifications.error("Binder scale not detected...Is this actor a Binder?");  
      return;
  }
  let vestigelevel = targetactor.system.scale.binder['vestige-level'].value;

  async function showDialog() {
    return new Promise((resolve) => {
        const findVestige = (item) => item.flags && item.flags.bindervestige;
      const foundVestige = targetitems.filter(findVestige);
  
      // Generate the list of options
      const options = foundVestige.map((item) => {
        return {
          label: item.name,
          value: item.id,
        };
      });
  
      new Dialog({
        title: "Bound Vestige Menu",
        content: `
          <div>
            <label for="options">Bound Vestiges (Select to dispel):</label>
            <select id="options" name="options" multiple>
              ${options.map((option) => `<option value="${option.value}">${option.label}</option>`)}
            </select>
          </div>
          <div>
            <label for="number">Vestige Level (Input to overwrite):</label>
            <input type="number" id="number" name="number" value=${vestigelevel}>
          </div>
        `,
        buttons: {
          ok: {
            label: "Import Vestiges",
            callback: (html) => {
              const selectedOptions = Array.from(html.find('#options')[0].selectedOptions).map((option) => option.value);
              const numberValue = parseInt(html.find('#number')[0].value);
  
              removeVestiges(selectedOptions);
              importVestiges(numberValue);
              resolve();
            },
          },
          cancel: {
            label: "Cancel",
            callback: () => {
              resolve();
            },
          },
        },
      }).render(true);
    });
  }
  
  function removeVestiges(options) {
    options.forEach((option) => {
        let removearray = targetactor.items.get(option).flags.bindervestige.grantedfeats;
    
        removearray.forEach((item) => {
            if (targetactor.items.getName(item))
            {
        targetactor.items.getName(item).delete()
            }
        });
        targetitems.get(option).delete()
    });
  }
    //Thanks to TheGiddyLimit for writing this
  function importVestiges(number) {
    (async () => {
      const ACTOR = targetactor;
      const ENTITY_PROP = "optionalfeature";
      const REQUIRED_TYPE_SET = new Set();

      for (let i = 1; i <= number; i++) {
        const value = `VS${i}`;
        REQUIRED_TYPE_SET.add(value);
      }
  
      // Load the brew
      const [brewDoc] = await BrewUtil2.pAddBrewFromUrl(URL_BREW);
      const sources = new Set(brewDoc.body._meta.sources.map(it => it.json));
      const content = (await DataLoader.pCacheAndGetAllBrew(ENTITY_PROP))
          .filter(it => sources.has(it.source));
  
      // Filter down to the desired feature types
      const contentFilt = content
          .filter(it => it.featureType.some(ft => REQUIRED_TYPE_SET.has(ft)));
  
      // Load the importer
      const importer = await game.modules.get("plutonium").api.importer.pGetImporter({prop: ENTITY_PROP, actor: ACTOR});
      await importer.pInit();
      await importer.pSetContent({optionalfeature: contentFilt});
       importer.render(true);
  })()
  }
  await showDialog();`

**Comment by TheGiddyLimit** [comment]
I see. That'll just about work as an item macro, I think; is there e.g. a convenient class feature you would want it attached to?

For context, the end result would be:

[item_macro.webm](https://github.com/TheGiddyLimit/homebrew/assets/25264887/69eeebae-d0cf-42b5-aa3a-3603c902390b)

This _does_ require the use of the [Automation Addon](https://github.com/TheGiddyLimit/plutonium-addon-automation), which comes with a bunch of extra module dependencies (MidiQOL and friends). If you're happy with that, you can make a new PR here with just your homebrew JSON, and I'll scrub up the macro and wire it in via the other module.

If you're _not_ happy with that, then, the next best option is probably sticking your macro in a git repo/gist/etc. of your own somewhere, and linking the resulting JS file with a `{@link ...}` in e.g. the description of the class. That way anyone using it can easily-ish find the macro too.

Foundry macros, generally, don't belong in this homebrew repo; the concessions to Foundry/Roll20 data here are very lightweight, and that's not something I want to change

**Comment by SLankoff** [comment]
Hmm...
I guess I'm not in love with the idea of being married to MidiQOL and company for something that theoretically doesn't need them. I'll go ahead and make a {@link in the class description to the macro on my own repo, then!
I appreciate you looking into it.

**Pull request closed without merging**
