### PR TITLE
Create Lambros009;Illivar's Guide to Nullification.json + Fix tokens for TTT and MMM:SS

### PR DESCRIPTION
**Pull request by Bowsori**

### CODE REVIEW

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
While deleting random files, including the file responsible for testing your PR, is a novel way to get your PR to pass tests, I don't think this is a changeset I can accept

**Comment by Bowsori** [comment]
I have literally no idea what happened, I'll take a look

**Comment by TheGiddyLimit** [comment]
What files did you mean to change/add? These?:
```
collection/Lambros009;Illivar's Guide to Nullification.json
creature/Kari Hoffren; Melvin's Minute Monsterium; Swamps & Sewers.json 
```

**Comment by Bowsori** [comment]
I also changed some links in the technomancer's textbook, sorry i'm not very good with git, but yes that should be the only changed files

**Comment by TheGiddyLimit** [comment]
Then I've now merged those in manually; I recommend you check out a fresh copy of the repo

**Pull request closed without merging**
