### PR TITLE
Wizard of the Citadel, by Worlds Beyond Number

### PR DESCRIPTION
**Pull request by JamesMcGowan-lab**
If you are using this on FoundryVTT, be warned that Spellcraft Secrets will not add automatically to levels without Wizard Advancements: Levels 5, 7, 11, 13, 15, and 17. You must simply import a secret from the Spellcraft Secrets Option manually.

### CODE REVIEW

**Comment by revilowaldow** [comment]
Re the note above see PLUT-BUG-167

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
was this supposed to have that

```json
"foundrySubclassFeature": [
    {
        "name": "Spellcraft Secret Options",
        "source": "WizardCitadelWBN",
        "className": "Wizard",
        "classSource": "PHB",
        "subclassShortName": "Citadel",
        "subclassSource": "WizardCitadelWBN",
        "level": 2,
        "isIgnored": true
    }
]
```

added..?

**Comment by JamesMcGowan-lab** [comment]
😑Yes it was, my apologies. I don't suppose you can add it in post?
If not, I'll just make a new files and fork it through

**Comment by TheGiddyLimit** [comment]
no prob, easily done

**Pull request merged**
