### PR TITLE
Add:   creature/Dragonix; Monster Manual Expanded II (v2).json

### PR DESCRIPTION
**Pull request by Spappz**
it is done
behold

### CODE REVIEW

**Comment by Spappz** [comment]
Can you please run that `attachedItem` script on this and/or send said script to me for a future PR? I did the statblock conversion waaay back when and I'd like to avoid duplicate work if possible 🥴

**Comment by revilowaldow** [comment]
It made it into test tags so you probably just want to run the in place thingy 

image

`node/tag-jsons.js inplace file="tob v2 blah.json"`

**Comment by revilowaldow** [comment]
Although that might just be checking it's a valid item

**Comment by TheGiddyLimit** [comment]
@Spappz eh? What're you looking to get checked, exactly?

**Comment by Spappz** [comment]
> @Spappz eh? What're you looking to get checked, exactly?

I noticed that creature brews already in the repo have had `attachedItem` filled out: https://github.com/TheGiddyLimit/homebrew/commit/cd1f3f0d070bb54e97ff8fcb93c680fbf4a3d2fe

I'm just asking that you re-run whatever script you used for that on this brew, since I haven't added any `attachedItem`s.

**Comment by TheGiddyLimit** [comment]
Ah roite, sure. The "script" in question is an ever-growing pile of mostly-commented-out spaghetti which isn't worth sharing; if you want to run the essence of the thing, then it's approximately:

```js
import * as fs from "fs";
// import lots of 5etools files here and hope for the best

const filename = "my-file.json"
const json = JSON.parse(fs.readFileSync(filename, "utf-8"))
json.monster.forEach(stats => AttachedItemTag.tryRun(stats))
fs.writeFileSync(filename, JSON.stringify(json, null, "\t"), "utf-8")
```

Will give it a run later today, though

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
