### PR TITLE
KibblesTasty Psion Update

### PR DESCRIPTION
**Pull request by CardboardandVinyl**
Includes new disciplines (Precognition, Nullification, Consumption), the Consuming Mind Subclass, and new Talents from the Kibbles' Compendium of Craft and Creation.

### CODE REVIEW

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
please pull or rebase onto the latest version

**Comment by CardboardandVinyl** [comment]
How do I rebase or pull onto the latest version? I don't see anything in the wiki for this.

**Comment by TheGiddyLimit** [comment]
unsure what wiki you're referring to, but rebasing is a normal git thing; see e.g. [https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by CardboardandVinyl** [comment]
Sorry, I had only looked at the 5eTools wiki. I'll try to learn how to do this and resubmit. Thanks!

**Pull request closed without merging**
