### PR TITLE
BREW-724: SGttEH: Heresy of Steel

### PR DESCRIPTION
**Pull request by revilowaldow**
image

- [x] Images & Maps
- [x] Game Master's Primer
- [x] The Cursed Convoy
	- [x] Adventure Text
	- [x] `mapRegions`
	- [x] `foundrySceneRoot`
- [x] In the Belly of the Beast
	- [x] Adventure Text
	- [x] `mapRegions`
	- [x] `foundrySceneRoot`
- [x] Appendix
- [x] License
- [x] NPC Tokens
- [x] Tag Image Dimensions

### CODE REVIEW

**Comment by revilowaldow** [comment]
So this failed (expected) on referencing homebrew-img assets in a different source folder.
There's going to be some brews that share assets.
Suggestion for this is something akin to this in the `_meta`:
```json
"dependencies": {
	"imgRepo": [
		"SGttEH"
	]
}
```

**Comment by TheGiddyLimit** [comment]
before I go making changes, does the stupid work? 

can you symlink a file and have it show up in `raw. ...`?

**Comment by revilowaldow** [comment]
You mean individually symlink the images across dirs?
That doesn't feel at all approachable to the lay user. 
And while this file only has 3 errors had I chosen to split out e.g. Steinhardt's Player Options book I'd be doing hundreds of individual links.

**Comment by revilowaldow** [comment]
Also no, you get a link file
image

**Comment by TheGiddyLimit** [comment]
fair enough; tested a relative symlink and it didn't work either

**Comment by TheGiddyLimit** [comment]
didn't much like sticking it in `_meta` as it's purely a static-testing thing, so: https://github.com/TheGiddyLimit/5etools-utils/blob/master/schema-template/homebrew.json#L300

```
"_test": {
  "additionalImageSources": [ "SGttEH" ]
}
```

likely going to be a few bugs with adding another "_meta-like" prop but those will all come out in the wash

**Comment by revilowaldow** [comment]
Thanks

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
