### PR TITLE
Ranges fixed

### PR DESCRIPTION
**Pull request by Matsozetex**
Added "A" properties to ranged weapons to display ranges.
Added "T" properties to thrown weapons to display ranges.
Previously had just used custom properties for these, but it seems the schema requires the in-built properties to be used to display ranges. It would be cool if there was a work around.

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Ah yes, I intended to fix that alongside having `dmg2` render without needing to specify things as "versatile". Will do that now. You can probably roll this back (as well as the versatile stuff? Up to you).

**Comment by Matsozetex** [comment]
I will get to it on the weekend, but for now take it as a intermediate fix until it is updated.

**Comment by TheGiddyLimit** [comment]
Sure, sure. It's not actually that simple either way; I think I'll need to add some template system to allow you to include whatever data you want when it renders. As a potential example:
```json
// Custom item property
...
"name": "Custom Thrown"
"template": "{{current_render}} thrown ({{item.range}})"
...
// Custom item property
...
"name": "Alt Damage"
"template": "{{current_render}} ({@dice {{item.dmg2}}})"
```
Thoughts? Things without specific templates would render as they do currently; just displaying the name.

**Comment by Matsozetex** [comment]
Looks good, I mean, anything that I could semi-properly do is pretty good.

**Pull request merged**
