### PR TITLE
Steinhardt's Guide to the Eldritch Hunt

### PR DESCRIPTION
**Pull request by revilowaldow**
- [x] Write an automated masking and deduplication pdf image extraction script
	- https://gist.github.com/revilowaldow/2d7a551685c5198fea42b285a2e30223
- [x] Document macros for handling `foundrySceneRoot`
	- https://gist.github.com/revilowaldow/782cd90e153f865b4afb9b8fd8b1a142
- [x] Steinhardt's Guide to the Eldritch Hunt
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Book Text
	- [x] Mechanical Content
		- [x] Races
		- [x] Class
			- [ ] Primary Resources
			- [ ] Specific Foundry Support
		- [x] Non-Jaeger Subclasses
			- [ ] Primary Resources
			- [ ] Specific Foundry Support
		- [x] Feats
		- [x] Backgrounds
		- [x] Spells
		- [x] Items
			- [x] Firearms
			- [x] Magic Variants
			- [x] Trick Weapons
				- [ ] Foundry `subEntities`
			- [x] Eldritch Carvings
		- [x] Monsters
		- [x] BBEGs
		- [x] Other
			- [x] Adventure NPCs
			- [x] Tokens
			- [x] Map Regions
			- [x] Grid Data
- [x] Player Options
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Book Text
	- [x] Mechanical Content
	- [x] Cross-Content Tags
	- [ ] `_copy` based implementation?
- [x] GM's Cheatbook
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Image Redirection
	- [x] Book Text
	- [x] Mechanical Content
	- [x] Cross-Content Tags
- [ ] Artbook
	- [x] Image Extraction
	- [ ] Image Cleanup
	- [ ] Book Text
	- [ ] Mechanical Content
	- [ ] Cross-Content Tags
- [x] Hunt Notes
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Card Creation
	- [x] Book Text
	- [x] Cross-Content Tags
	- [x] Backport Fluff Images
- [x] Trick Weapons Cards
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Card Creation
	- [x] Book Text
	- [x] Mechanical Content
	- [x] Cross-Content Tags
- [x] Eldritch Moons Cards
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Card Creation
	- [x] Book Text
	- [x] Mechanical Content
	- [x] Cross-Content Tags
- [x] Map of Luyarnha
	- [x] Image Extraction
	- [x] Image Cleanup
	- [x] Book Text
	- [x] Map Regions
	- [x] Cross-Content Tags
- [x] Character Sheets
	- [x] Jaeger Sheet
	- [x] Character Sheet 1
	- [x] Character Sheet 2
- [x] General
	- [x] Tag Image Dimensions

### CODE REVIEW

**Comment by Spappz** [comment]
Suggestion for @TheGiddyLimit re: [da5700a](https://github.com/TheGiddyLimit/homebrew/pull/2063/commits/da5700a3edd1b34ebd3a3d7ff63e20609dcb7527)
Add an extra part to `clean-and-test.js` file to, in addition to the usual 5etools-utils stuff, also verify that new JSON files use a filename matching `/^[^;]+; .+\.json$/` (case-sensitive because `.JSON` makes me sad 😎)

**Comment by revilowaldow** [comment]
> in addition to the usual 5etools-utils stuff

Probably reworking `_BrewTesterFileExtensions` (which is already case sensitive for .json?) into `_BrewTesterFileNames`
https://github.com/TheGiddyLimit/5etools-utils/blob/284b3b807c76df6abb5fdc5f26aa84f1e4355a28/lib/BrewTester.js#L74C7-L74C33

**Review by TheGiddyLimit — APPROVED** [review]
can't believe they called a spell school "bone-o-mancy"

**Comment by revilowaldow** [comment]
image

**Pull request merged**
