### PR TITLE
Add MonkeyDM; Oath of the Eldritch Hunt

### PR DESCRIPTION
**Pull request by AmbyNavy**
Got this in the mailing list in waiting for Steinhardt's Guide to the Eldritch Hunt, cool little subclass that I'll be running!

### CODE REVIEW

**Comment by AmbyNavy** [comment]
npm failed however i dont know if it was because of my file?

**Comment by AmbyNavy** [comment]
Okay nevermind the spells aren't working (fuck) give me a little to fix that lmao

**Comment by AmbyNavy** [comment]
Ok now it works flawlessly in Foundry and i see no issues in 5etools so 🤷

**Comment by AmbyNavy** [comment]
fixed now
thank god
i can rest

**Review by TheGiddyLimit — APPROVED** [review]
a fine rollercoaster

**Pull request merged**
