### PR TITLE
Custom Backgrounds

### PR DESCRIPTION
**Pull request by DaveParkinglot**
These backgrounds are basically the 2024 backgrounds but I added suggested characteristics similar to the 2014 backgrounds :)

Also sorry for all the pulls, I'm very bad at Github

### CODE REVIEW

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by TheGiddyLimit** [comment]
would still be better with a bit of `_copy` abuse, but it'll do

**Comment by DaveParkinglot** [comment]
> would still be better with a bit of `_copy` abuse, but it'll do

I figured having the Source be different would be enough. Plus if I had "Acolyte_Copy" in my game, my players would get confused lol

**Comment by TheGiddyLimit** [comment]
`_copy` as in the thing that allows you to copy and modify an existing entity:

- https://github.com/5etools-mirror-3/5etools-src/blob/main/data/backgrounds.json#L2278
- https://github.com/TheGiddyLimit/homebrew/blob/master/_doc/Spec_Copy.md

**Comment by DaveParkinglot** [comment]
Oh good call, I didn't realize it could be that easy. I'll take a look

**Pull request merged**
