### PR TITLE
Aura; Homebrew File

### PR DESCRIPTION
**Pull request by Aura-6931**
[Aura_s_HB_Folder.json](https://github.com/TheGiddyLimit/homebrew/files/13519802/Aura_s_HB_Folder.json)

### CODE REVIEW

**Review by Aura-6931 — COMMENTED** [review]
[Aura_s_HB_Folder.json](https://github.com/TheGiddyLimit/homebrew/files/13540139/Aura_s_HB_Folder.json)

**Comment by TheGiddyLimit** [comment]
it's something you'd do in _git_; I'm not familiar with if/how you'd do it in git_hub_

probably go to your branch, press `.`, and move your files into the `creatures` folder using the editor

**Comment by Aura-6931** [comment]
> it's something you'd do in _git_; I'm not familiar with if/how you'd do it in git_hub_
> 
> probably go to [your branch](https://github.com/Aura-6931/homebrew/tree/aura%3B-Lucero-Nero.json), press `.`, and move your files into the `creatures` folder using the editor

Hey thanks for your response! I was directed to attempt to use GIT Desktop and followed the instructions on how to place my HB into creatures. Does this appear right?

https://github.com/Aura-6931/homebrew/commit/9eb736af90a4166063b91e9ba6ec5d3404c1a39f and https://discord.com/channels/363680385336606740/493154206115430400/1180967197032579212

**Comment by TheGiddyLimit** [comment]
👍 much better

**Comment by Aura-6931** [comment]
> 👍 much better

Hey hey thanks again for replying! Just as a heads up, may have accidentally created a new pull request...

#1924 if that might make it weird we can close that

**Pull request closed without merging**
