### PR TITLE
Add Jonoman3000; The Fallen.json

### PR DESCRIPTION
**Pull request by AmbyNavy**
i swear if this is broken i will scream all i did was replace text in my warlock subclass template

### CODE REVIEW

**Comment by AmbyNavy** [comment]
*screams*

**Comment by AmbyNavy** [comment]
i am going to commit holy shotgun throat ritual

**Comment by AmbyNavy** [comment]
no cobain handshake for me today it seems

**Comment by AmbyNavy** [comment]
i fucking hate foundry data sometimes frfr

**Comment by TheGiddyLimit** [comment]
aren't you like a professional developer or something

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by AmbyNavy** [comment]
if you dont break something and make angry, depressive comments on your own PR are you even developing?

**Comment by TheGiddyLimit** [comment]
I simply
```
git commit --amend
git push --force
```
and pretend I got it right the first time

**Pull request merged**
