### PR TITLE
Overhaul Ar4

### PR DESCRIPTION
**Pull request by revilowaldow**

### CODE REVIEW

**Comment by revilowaldow** [comment]
Does this need the utils ver bumping for changes to class equipment?
I see c2218df making changes but 4f208d9 only committed the `package-lock` not the `package.json`

**Comment by TheGiddyLimit** [comment]
nah just a junk schema changed; should now be fixed

**Review by TheGiddyLimit — APPROVED** [review]
ta for the sample fixing

**Comment by revilowaldow** [comment]
> ta for the sample fixing

No problem, looking forward to seeing what insane sample bastion facility you come up with 😏

**Pull request merged**
