### PR TITLE
Yesterday's Class Passives and Feat Tiering

### PR DESCRIPTION
**Pull request by yesterdaydnd**
Hello. I would like to add my homebrew to the repository
If there's any problem, let me know.
Thanks

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Would you be happy with these files being combined into one, and put in the `collection` directory? There's no functional difference, it just helps to keep things organised.

**Comment by yesterdaydnd** [comment]
Sure. Originally I had them merged, but I thought they had to be placed on different categories since there's both feats and optional features. If i put them together and place it on the collections folder it will show up correctly at the website anyway right? I'll merge them

**Comment by yesterdaydnd** [comment]
Done!
I believe it should be correct now.
Thanks!

**Comment by yesterdaydnd** [comment]
Minor fix

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
