### PR TITLE
Tome of Heroes by Kobold Press

### PR DESCRIPTION
**Pull request by Foopsie42**
WIP of Tome of Heroes conversion

Description
Tome of Heroes contains a variety of options to create unique characters:

• 80 new subclasses, including the Circle of Bees, Way of the Unerring Arrow, Path of Hellfire, School of Black Powder, and Pugilist • 11 new races and 40 subraces for pre-existing and new races, from deer-like alseid, to mechanical gearforged, to aquatic gnomes and arctic elves 
• 19 new backgrounds, including diplomat, freebooter, gamekeeper, and innkeeper • A shops’ worth of equipment, such as firearms, chakrams, glidecloaks, and bombs, plus mounts and clockwork companions • New ways of using magic, from manipulating magical plants to drawing draconic runes
• 139 new spells, including fuse armor, conjure fireflies, and steam gout

To Do:

- Downtime activities
- Adventuring gear
- Adventuring rules
- Creature stat blocks

### CODE REVIEW

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
Please move the file into `collection/`

**Comment by Foopsie42** [comment]
> Please move the file into `collection/`

fixed

**Comment by Foopsie42** [comment]
> Please move the file into `collection/`

fixed

**Comment by Foopsie42** [comment]
@TheGiddyLimit for some reason it doesn't go through

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
