### PR TITLE
Spappz's Bimonthlyish Brew Extravaganza

### PR DESCRIPTION
**Pull request by Spappz**
It's that time again. This will probably fail the tests, but note the proposed change to the schema.
- Add `creature/Nerzugal Role-Playing; Nerzugal's Extended Bestiary.json` and associated `_img/NerzugalsExtendedBestiary` folder
- Escape unsafe URL characters in a number of brews that I've touched in the past (thanks @ Dusk)
- Tagging & typos for HWCS and CComp
- Moved `Andrew Cawood; Monsters of the Underworld.json` to a more appropriate folder (`creature`)
- MME3: add page numbers, move all fluff to `monsterFluff`, and improve a third of the fluff in the process
- **Update schema to account for the `scalarMultXp` mode**, which NEB uses (documented [here](https://github.com/TheGiddyLimit/homebrew/blob/master/_doc/Spec_Copy.md) and functional on 5eT when I tested; repo passed the schema test with my amendments)

### CODE REVIEW

**Comment by Spappz** [comment]
I'm surprised this passed the tests; I guess it checks against the schema on the to-merge branch? Feels a bit dangerous 👀💦

**Comment by TheGiddyLimit** [comment]
That's Working As Intended:tm:, although modifying the schemas in this brew repo is _not_ intended/recommended, as they're merely compiled output from a script in the 5etools repo.

Have added the missing modes, if you'd like to merge/discard your schema changes.

**Comment by Spappz** [comment]
Got it. If I find anything else schema-y, should I PR the changes to the Github mirror, or just message you about them?

**Comment by TheGiddyLimit** [comment]
Either works for me 👍

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
