### PR TITLE
Kibb craft

### PR DESCRIPTION
**Pull request by cadowtin**

### CODE REVIEW

**Comment by cadowtin** [comment]
Added Kibb Craft poison

added Ancest weapons effects (for 1st lvl)

**Comment by revilowaldow** [comment]
@cadowtin please could you make sure that you're getting yourself allocated to requests on the discord and then marking those requests as resolved to avoid people doubling up on conversions by mistake. For example I'd just started on Kibble's Crafting guide.

**Comment by cadowtin** [comment]
Hi, @revilowaldow sorry about that. had just been kind of uploading any conversions I started on/used for my own games. Didn't realize there was a system.

**Comment by cadowtin** [comment]
@revilowaldow I now know about that channel and i'll use it to avoid stepping on your or anyone else's coding toes. Added a note of sections that are still WIP, if you're still working on it. Again, sorry, My Bad.

**Comment by revilowaldow** [comment]
> @revilowaldow I now know about that channel and i'll use it to avoid stepping on your or anyone else's coding toes. Added a note of sections that are still WIP, if you're still working on it. Again, sorry, My Bad.

No no, no need to apologies! I've spotted you adding loads of things in the past so thanks for doing all of that! 
You're not stepping on any toes and you seem to be well ahead of me, thanks for adding the progress list that's really useful!
Feel free to keep working on it, it was just something I liked the look of and thought I'd give a go, no particular attachment.

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
