### PR TITLE
Adding Kibbles' Generic Elemental Spells

### PR DESCRIPTION
**Pull request by TheAvonian**
Didn't add any spells specific to only classes from KibblesTasty's homebrews but I'm pretty sure that was only 1 spell. Anyone else is free to change that ofc.

### CODE REVIEW

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
please avoid committing changes to the `_generated` files

ideally, since you've got one commit, `--amend` it and force-push

**Comment by TheAvonian** [comment]
Ahh was wondering about that, I just fixed it though! Thanks for letting me know.

**Review by TheGiddyLimit — APPROVED** [review]
perfect, tyvm

**Comment by revilowaldow** [comment]
There's spells can already be found in https://github.com/TheGiddyLimit/homebrew/blob/master/spell/KibblesTasty%3B%20Kibbles'%20Casting%20Compendium.json

Which includes `otherSources` information regarding Generic Elemental Spells. This addition is unnecessary duplication.

**Pull request merged**
