### PR TITLE
Griffon's Saddlebag Year 4 items

### PR DESCRIPTION
**Pull request by unknown117343**

### CODE REVIEW

**Comment by unknown117343** [comment]
@TheGiddyLimit Is the linting workflow supposed to kick off automatically?

**Comment by TheGiddyLimit** [comment]
there's no auto-run for first time contributors, sadly

**Comment by TheGiddyLimit** [comment]
💥 

if you update the PR it still won't auto-run, fwiw, so you might want to `npm i` -> `npm t` locally

**Comment by revilowaldow** [comment]
Or use vscode with the extension, there's quite a bit to fix in there. 
Stuff with `__prop` will need to be moved to the right array, likely `magicvariant`. 
People in #brew conversion in the discord can help if you need guidance
image

**Comment by unknown117343** [comment]
fixed the issues, thank you

**Review by TheGiddyLimit — APPROVED** [review]

**Pull request merged**
