### PR TITLE
Update Blood Hunter 2020

### PR DESCRIPTION
**Pull request by EldritchTranslator**
Updated BH2020 with the edits from Feb 2022 on DDB

### CODE REVIEW

**Comment by revilowaldow** [comment]
This should probably be a new file called BH2022...

**Comment by TheGiddyLimit** [comment]
Should it? What's the justification for/against? Thoughts as the converter, @MrVauxs ?

**Comment by EldritchTranslator** [comment]
Considering it's really mostly an update to clarify some abilities and updating them with new warlock patrons, I didn't think of making a separate file, as with like, the original bloodhunter. It looks like I rewrote a lot, but they rewrote basically the same things.

**Comment by MrVauxs** [comment]
> Should it? What's the justification for/against? Thoughts as the converter, @MrVauxs ?

image


I specifically **didn't** update it because it wasn't an official update, but one made by D&DB exclusively for D&DB. 
It should be it's own separate file.

**Comment by TheGiddyLimit** [comment]
So noted. We'll go with a second copy. `... (2022)`, then. Closing for now; @EldritchTranslator feel free to either update this PR and it can be re-opened/merged, or create a new one. Or if you want me to do it, let me know

**Comment by EldritchTranslator** [comment]
Ah, forgot about this. I'll do another PR in a bit, sorry

**Pull request closed without merging**
