### PR TITLE
Uwu adds Hewwschew of the Void

### PR DESCRIPTION
**Pull request by revilowaldow**
Closes Issue #1529

### CODE REVIEW

**Comment by revilowaldow** [comment]
image
New error is great btw <3

**Review by TheGiddyLimit — APPROVED** [review]
very spappzesque title

**Comment by revilowaldow** [comment]
Take a look at the source url

**Comment by TheGiddyLimit** [comment]
wish I hadn't

**Comment by revilowaldow** [comment]
Well on the bright side #1529 can be closed now

**Pull request merged**
